"""empty message

Revision ID: f3ba5c74fcfb
Revises: 8a37b88260b7
Create Date: 2021-09-01 23:43:20.864105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ba5c74fcfb'
down_revision = '8a37b88260b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('interview_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cat', 'interview', ['interview_id'], ['id'])
    op.drop_constraint('interview_cat_id_fkey', 'interview', type_='foreignkey')
    op.drop_column('interview', 'cat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('cat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('interview_cat_id_fkey', 'interview', 'cat', ['cat_id'], ['id'])
    op.drop_constraint(None, 'cat', type_='foreignkey')
    op.drop_column('cat', 'interview_id')
    # ### end Alembic commands ###
