"""empty message

Revision ID: 1049ffb32a2c
Revises: 1daaf778aa79
Create Date: 2021-09-08 14:16:06.113657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1049ffb32a2c'
down_revision = '1daaf778aa79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'interview', 'pet', ['pet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview', type_='foreignkey')
    # ### end Alembic commands ###
