"""empty message

Revision ID: 17b570cb7e3e
Revises: 8174bc64ccca
Create Date: 2021-09-05 00:44:50.958648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b570cb7e3e'
down_revision = '8174bc64ccca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
