"""empty message

Revision ID: 9d341c0a41c0
Revises: 
Create Date: 2021-09-01 21:26:23.579424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d341c0a41c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'interview', 'owner', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.drop_column('interview', 'owner_id')
    # ### end Alembic commands ###
