"""empty message

Revision ID: 18008c3c8707
Revises: 9d341c0a41c0
Create Date: 2021-09-01 22:25:43.881822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18008c3c8707'
down_revision = '9d341c0a41c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breed', 'location_of_origin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breed', sa.Column('location_of_origin', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
