"""empty message

Revision ID: 1daaf778aa79
Revises: cd780749370d
Create Date: 2021-09-05 22:11:55.059938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1daaf778aa79'
down_revision = 'cd780749370d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pet_name_key', 'pet', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pet_name_key', 'pet', ['name'])
    # ### end Alembic commands ###
