"""empty message

Revision ID: 57598d48e1d5
Revises: cb5c4922c54d
Create Date: 2021-09-04 00:35:56.513628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57598d48e1d5'
down_revision = 'cb5c4922c54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('breed', 'specie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('breed', 'specie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
