"""empty message

Revision ID: 5d93f3d60c6a
Revises: 2dd9f3cd34a7
Create Date: 2021-09-04 00:01:32.597510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d93f3d60c6a'
down_revision = '2dd9f3cd34a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pet', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('pet', 'vaccinated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pet', 'letter_box_trained',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(None, 'pet', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pet', type_='unique')
    op.alter_column('pet', 'letter_box_trained',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pet', 'vaccinated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pet', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
