"""empty message

Revision ID: 8a37b88260b7
Revises: 906a0e84b35c
Create Date: 2021-09-01 22:42:30.540388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a37b88260b7'
down_revision = '906a0e84b35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('avatar', sa.String(length=500), nullable=True))
    op.drop_column('owner', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('owner', 'avatar')
    # ### end Alembic commands ###
