"""empty message

Revision ID: 906a0e84b35c
Revises: 18008c3c8707
Create Date: 2021-09-01 22:36:58.591842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906a0e84b35c'
down_revision = '18008c3c8707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('age_in_months', sa.Integer(), nullable=False))
    op.drop_column('cat', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('cat', 'age_in_months')
    # ### end Alembic commands ###
