"""empty message

Revision ID: a68919462b0a
Revises: f3ba5c74fcfb
Create Date: 2021-09-03 18:56:55.387506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68919462b0a'
down_revision = 'f3ba5c74fcfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('breed', sa.Column('specie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'breed', 'specie', ['specie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'breed', type_='foreignkey')
    op.drop_column('breed', 'specie_id')
    op.drop_table('specie')
    # ### end Alembic commands ###
