"""empty message

Revision ID: cb5c4922c54d
Revises: 5d93f3d60c6a
Create Date: 2021-09-04 00:31:27.445778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5c4922c54d'
down_revision = '5d93f3d60c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('breed', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('specie', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specie', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('breed', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
