"""empty message

Revision ID: cd780749370d
Revises: ef2a7bc7622b
Create Date: 2021-09-05 13:59:59.880902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd780749370d'
down_revision = 'ef2a7bc7622b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pet_user_id_fkey', 'pet', type_='foreignkey')
    op.drop_column('pet', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pet_user_id_fkey', 'pet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
