"""empty message

Revision ID: ee6724b4da06
Revises: 57598d48e1d5
Create Date: 2021-09-04 00:54:49.979868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6724b4da06'
down_revision = '57598d48e1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pet', 'breed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pet', 'breed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
