"""empty message

Revision ID: ef2a7bc7622b
Revises: 17b570cb7e3e
Create Date: 2021-09-05 11:57:23.379564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef2a7bc7622b'
down_revision = '17b570cb7e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('interview', 'time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('interview', 'pet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview', 'pet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interview', 'time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('interview', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
